

## Tsuga heterophylla

https://www.fs.fed.us/database/feis/plants/tree/tsuhet/all.html

Western hemlock is generally a good
cone and seed producer.  Cones may form on open-grown trees that are
less than 20 years old, but good cone crops usually do not occur until
trees are between 25 and 30 years old.  Individuals usually produce some
cones every year and heavy cone crops every 3 or 4 years.  Each cone
contains 30 to 40 seeds.  The number of viable seeds ranges from fewer
than 10 to approximately 20 per cone [18,56].  Seeds are light and
small, ranging from 189,000 to 508,000 cleaned seeds per pound, with an
average of 260,000 seeds per pound (371,000-900,000/kg, average 530,000
seeds/kg) [56,63].

Western hemlock seeds have large wings enabling them to be distributed
over long distances.  In open, moderately windy areas, most seeds fall
within 1,968 feet (600 m) of the parent tree.  Some seeds can travel as
far as 3,772 feet (1,150 m) under these conditions.  In dense stands,
most seeds fall much closer to the base of the tree [56].

The reproductive cycle of western hemlock occurs over 15 to 16 months
from the time of cone initiation in early summer, until seeds are shed
in the fall of the following year. Fertilization and seed development
occur in the second year.  Phenology varies between coastal and interior
regions [56,57,76].  Trees in the interior region or at higher
elevations begin development later in the spring and complete
development earlier in the fall than do trees growing in coastal and
low-elevation regions [56].

At low-elevation coastal British Columbia locations, pollination
commonly occurs in early to mid-April, whereas in the interior of
British Columbia, it may occur from May until mid-June.  Records from
western Washington and Oregon show that pollination may occur from
mid-April until late May [56].  Fertilization occurs in coastal western
hemlock about mid-May.  The time from pollination to seed release ranges
from 120 to 160 days in western hemlock.  It can vary according to
weather and temperature during cone maturation.  Dry, warm weather in
late summer may cause more rapid drying and earlier opening of cones
with consequently, earlier seed release.  Wet, cool weather may delay
cone opening and seed release.  Most seeds are shed in the fall when
cones first open [50,56,76].  Cones may close in wet weather and reopen
more fully with subsequent dry weather.  As a result, seeds may be shed
throughout the winter or even during the next spring.  Mature cones
often persist on the tree throughout the second year but contain few
viable seeds [56,57].


## Tsuga mertensiana


#### https://depts.washington.edu/propplnt/Plants/tsugahet.htm

Seeds are usually fully ripe by mid to late September, although cone scales do not open until late October (Silvics of North America 1990).


#### https://www.fs.fed.us/database/feis/plants/tree/tsumer/all.html


Seed production and dissemination:  Mountain hemlock begins producing
seed at about age 20.  Mature trees 175 to 250 years old produce
moderate to very heavy cone crops at about 3-year intervals in Oregon
and Washington, but crops may be complete failures in other years [49].
Cones average about 70 to 100 seeds [28].  There are 102,000 to 207,000
seeds per pound [70].  On one study site located at Santiam Pass,
Oregon, the largest number of cones counted was 1,700 on a 20-inch (51
cm) mountain hemlock [28].  Over 1,000 cones per tree were counted on
many other trees during the 5 year study period.  Seed production is
better during normal to wet growing seasons than during dry growing
seasons [49].

Mountain hemlock's winged seeds are dispersed primarily by wind.
Germination is epigeal and occurs on snow, or mineral or organic soil if
sufficient moisture is available [49].  Germination rates range from 47
to 75 percent [28,49].  Cold stratification of mature seeds shortens
incubation time and may substantially increase germination [62].  Heavy
seeds germinate more rapidly than seeds with low percent dry weight.
Along the eastern high Cascades in Oregon, seed viability of mountain
hemlock varied from 36 to 76 percent over a 2-year period [49].

Seedling development:  Young seedlings grow best in partial shade and
early development is often slow.  Seedlings are relatively drought
intolerant [2].  Increasing light intensity and day length increase
seedling height but delay or prevent terminal bud formation under
shelter.  Healthy mountain hemlock saplings respond well to release, in
both diameter and height growth.  Seedlings and small saplings of
mountain hemlock tolerate heavy snowpacks well [49].


SEASONAL DEVELOPMENT : 
Mountain hemlock has a 2-year reproductive cycle.  Pollination occurs in
the spring or early summer of the second year [55].  Mountain hemlock
releases pollen in June in the Cascade Range in Oregon, from mid-June to
mid-July in British Columbia, and from mid-May to late June in Alaska
[49].  Fertilization occurs from about late July to early August in
British Columbia.  Reproductive buds can easily be identified in the
late summer and fall.  Cones ripen and open from late September to
November [49,56].  In the Bitterroot Mountains of Idaho cones ripen in
August [62].  In Montana cones open and release the wide-winged seeds in
September or October and then abscise [44].


## Abies amabilis

#### https://www.fs.fed.us/database/feis/plants/tree/abiama/all.html

The timing of cone collection (mid to late August) is important because
cones disintegrate as they mature.  Felling and topping are not
successful collection methods.  The cones are susceptible to molding and
heat build-up if sacked when wet [18].  Calcid flies (Pregastigmus spp.)
infect cones of Pacific silver fir [59].  Franklin [24] discusses a cone
drying schedule and seed storage conditions.  Seeds are delicate and
their coats may be damaged when drying [16].  Edwards [17] reviews
techniques of seed extraction, viability, and germination testing.
Cleaned seeds range from 17,200 to 45,860 seeds per pound (7,800-20,800
seeds/kg) [14], and average 11,000 to 13,800 seeds per pound
(4,590-6,210 seeds/kg) [24].  A stratification period of 21 to 28 days
is required.  Seeds should be sown in spring at a density of 62.5 to 125
per acre (25-50 per ha) and approximately 0.25 inch (0.64 cm) deep,
depending on the site [24].  Arnott and Mathews [7] discuss nursery
practice for Pacific silver fir.  Highest stocking can be achieved on
bare soil [34].  Seedlings planted in logged areas have done poorly [6].



REGENERATION PROCESSES : 
Pacific silver fir reproduces only from seed [14].  Seed production
begins at 20 to 30 years of age [14].  There are approximately 400 seeds
per cone; percentage of sound seed ranges from 6.3 to 35 percent
[14,24].  Good seed crops are generally produced every 2 to 3 years
[14,59], but intervals between good seed crops may be as long as 6 years
according to some reports [17,25].  Production of seed is poor due to
the high frequency of low pollen production years [14].  Complete crop
failures sometimes occur [59].

Pacific silver fir requires 2 years to complete its reproductive cycle
[63].  It is capable of self-fertilization [14,38].  Wind dispersion of
seed is inefficient because of seed size and cone disintegration [59].
Germination occurs in the spring.  Germination can occur on a variety of
substrates such as litter, rotten wood, moss, organic and mineral soils,
and fresh volcanic tephra.  Cool, moist sites are optimal for
germination, but full sunlight produces maximum growth [14].  Pacific
silver fir takes 9 years to reach breast height on average sites [14], 5
to 9 years on more favorable sites, and up to 80 years when severely
suppressed [36].


SEASONAL DEVELOPMENT : 
Pacific silver fir has a 2-year reproductive cycle.  In May of the first
year, buds are initiated; differentiation follows in July.
Megagametophytes and ovuliferous scales are initiated in mid-July and
mid-August, respectively.  Both are dormant by November and remain
dormant until April of the second year, at which time development of the
pollen-cone and seed-cone buds is resumed [63].  Pollination occurs in
May and is well synchronized with female receptivity [14,63].
Fertilization occurs in early July, 4 to 5 weeks after pollination.  In
early August, meristems and cotyledons of embryos develop and mature by
the end of the month.  Cones change from green to purple at maturity
[6,63].  As cones mature, they disintegrate before the seed can be
dispersed, which occurs in September and October [24,63].


## Abies procera

#### https://www.fs.fed.us/database/feis/plants/tree/abipro/all.html

REGENERATION PROCESSES : 
Noble fir begins producing seed at 25 to 30 years of age, but
large-volume crops are not produced until age 35 to 50 [14,17,45].  Good
seed crops are produced at 3- to 6-year intervals [7,14,17,45].

Seed quality is often poor [18].  Cone crops need to be medium size or
better for sound seed to exceed 10 percent [17].  Cone and seed
collection, drying, and storage techniques are discussed in the
literature [7].  Insects that cause some losses are also discussed [45].
Seeds are disseminated by wind.  Seeds can be dispersed up to 2,000 feet
(367 m) from the source, but most fall within one or two tree height of
the parent [7,17].

Seeds usually germinate in the spring after they are shed [1,19].  Seeds
remain viable for only 1 year.  A mineral seedbed in relatively open
areas is favorable for seedling establishment and growth [22].
Competing vegetation and frosts deter regeneration of noble fir [18].

As with other firs, initial juvenile growth is slow [16,17,27].  Noble
fir requires 5 to 12 years to reach breast height, depending on site
condition [16,18,27].  Growth from a sapling stage to maturity is rapid,
allowing noble fir to attain site dominance [27,43].  As the tree ages,
growth slows [27].  Where they occur together, noble fir growth exceeds
Douglas-fir after 100 years [24].

Noble fir does not reproduce vegetatively [18].

SEASONAL DEVELOPMENT : 
Male and female bud burst occurs in May and early June, and is followed
by pollen shed in June and early July [14,18,21,45].  Pollen shedding
and female receptivity are well synchronized in noble fir [21,45].
Cones ripen in mid- to late September, and seed dispersal begins in
early October [14,21,45]. Seed dissemination requires wind action or
other branch movement to disturb the cone [7,21].  Height growth is
greatest in July [27].


## Abies concolor

#### https://www.fs.fed.us/database/feis/plants/tree/abicon/all.html

Cone and seed production: Cone and seed production vary with tree size, age and dominance. White fir trees can begin bearing cones at 40 years and continue beyond 300 years [178]. The best producers are mature, healthy dominants in the 12 to 35 inch (30-89 cm) d.b.h. range [120,178]. Cone production is higher on trees near openings [119] and on trees following release [178]. Immature trees can produce heavy seed crops, but their production is more erratic than that of mature trees [119,178]. Pole-sized trees in dense stands will not produce cones unless their leaders reach full sunlight. In mixed conifer forests of California only 4% of understory white fir between 3.6 and 7.5 inches (9.1-19 cm) in diameter produce cones [104]. In Oregon and California, heavy seed crops in white fir are borne on a 3- to 9- year cycle, with fair to good crops occurring every 2 to 5 years, and bumper crops every 5 to 9 years [178]. In the Rocky Mountains, medium to heavy seed crops are produced every 2 to 4 years [104]. Cone production patterns may be different on extreme sites [110,120,157,178]. Because cones are borne on the uppermost part of the crown, any top damage caused by insects, diseases or mechanical agents (e.g. wind and snow) directly reduces cone production. Cones produce about 185 to 295 seeds apiece [104,119]. Seed numbers can reach 600,000/acre (1.5 million/ha) or more where white fir is a site dominant [112,178], and as many as 220,000 where white fir is a minor overstory component [181].

Seed predation: Insects that feed on cones and seeds may seriously reduce yield. Seed chalids typically destroy 8 to 10% of white fir seeds and have destroyed up to 60% of a crop [108]. Cone moths, cone midges, and cone maggots also reduce yields [119]. In California and Oregon, the Douglas squirrel cuts and caches cones, but generally takes less than 1% of the cone crop [106].

Seed dispersal: White fir seeds are released and disseminated by wind as the cone disintegrates on the tree in the fall. Because white fir seed has a short, broad wing relative to its weight, if falls more rapidly and travels a shorter distance from the tree than many of its associated species. Downwind seed spread into an opening is about 1.5 to 2 times the height of the tree [119,178,203]. A small percentage of seeds may be transported greater distances by strong or gusty winds [218].

 SEASONAL DEVELOPMENT:
White fir requires 2 years to complete its reproductive cycle. Cones are initiated in mid-May of the 1st year as microscopic primordia within vegetative buds. Bud differentiation occurs in midsummer and separate seed-cone and pollen-cone buds develop until each becomes dormant in the fall [300]. During the spring of the 2nd year, cone buds resume growth and conelets are recognizable in early May. In Oregon and California, second year reproduction phenology proceeds with flowering in late May to early June, and fertilization occurring shortly thereafter [108,178,235]; cones reaching full size by early to late August [104,235]; and seed dispersal beginning in late September to early October [106,119].

In New Mexico, white fir growing with Douglas-fir completed bud elongation by May 4, and most of its flush extension by the middle of June, and exhibited about twice the flush growth of Douglas-fir over a 5-year period [56]. Flowering of Rocky Mountain white fir may extend into July at higher elevations. Female cones reach full size in late summer and turn brown when mature. The seed matures in September, up to 3 weeks before seedfall [178,235]. 


## Pseudotsuga menziesii

#### https://www.fs.fed.us/database/feis/plants/tree/psemenm/all.html

REGENERATION PROCESSES : 
Cone and seed production:  Appreciable seed production begins at 20- to
30-years of age in open-grown coast Douglas-fir.  Seed production is
irregular.  Over a 5- to 7-year period, stands usually produce one heavy
crop, a few light or medium crops, and one crop failure [31].  Even
during heavy seed crop years, only about 25 percent of trees in closed
stands produce an appreciable number of cones [31].  Each cone contains
26 to 50 seeds [59].  Seed size varies greatly; average number of
cleaned seeds per pound varies from 32,000 to 40,000 (70,400-88,000/kg)
[59].  Seeds from the northern portion of coast Douglas-fir's range tend
to be larger than seed from the south [31].

Dispersal:  Douglas-fir seeds have a relatively large, single wing and
are primarily dispersed by wind and gravity.  Most fall within 110 yards (100 m)
of the parent tree, but some may travel much greater distances.  On rare
occasions, sites more than 0.5 mile (0.8 km) from a seed source have
reseeded after cutting [19].  Mice, chipmunks, and squirrels
disperse small amounts of seed [28].  Clark's nutcrackers also disperse
Douglas-fir seeds.  Unretrieved seeds in Clark's nutcracker caches may
have a better change of establishment than wind-dispersed seed [80,81].

SEASONAL DEVELOPMENT : 
The phenology of coast Douglas-fir is influenced greatly by latitude and
elevation.  Flowering occurs during March and April in the warmer parts
of its range and as late as May or June in colder areas [31].  The cones
mature in one growing season and are normally ripe by late August or
early September.  Cones open as they dry, so wet fall weather can delay
seedfall.  Approximately 70 to 90 percent of the seeds are dispersed by
November 1, with the remainder falling during winter [59].  Cones remain
on the tree 1 or more years after seed dispersal [59].


## Picea sitchensis

#### https://www.fs.fed.us/database/feis/plants/tree/picsit/all.html

REGENERATION PROCESSES : 
Sitka spruce reproduces both sexually and asexually.  Sexual maturity
varies from 20 to 40 years.  Dispersal of seeds is moisture dependent;
when the ripe cones dry the seed is dispersed, and when the cones become
wet again they close.  To avoid loss of seed, cones should be collected
soon after ripening [50].  The seeds are small with a mean of 210,000
cleaned seeds per pound (467,000/kg) [24].  The germination rate is 54
percent, but this can be raised to 66 percent by moistening the
germination medium with a 0.2 percent potassium nitrate (KNO3) solution
[50].

EASONAL DEVELOPMENT : 
Flowering and seed dispersal dates for Sitka spruce in Alaska and Oregon
are as follows [22,50]:

         Flowering       Fruit Ripens                  Seed Dispersal

Alaska   April to June   late Aug. to mid-Sept.        Starts in Oct

Oregon   May                  Aug                      Oct. to Spring

Seed dispersal is moisture dependent; when the ripe cones dry dispersal
begins.  The majority (73 percent) of seed are dispersed in the first 6
weeks; the remainder are released over the next year [22].


## Pinus ponderosa

https://www.fs.fed.us/database/feis/plants/tree/pinponp/all.html


## Thuja plicata


### https://www.fs.fed.us/database/feis/plants/tree/thupli/all.html

EGENERATION PROCESSES : 
Seed production and dissemination:  Western redcedar reproduces from
seeds more readily in open, disturbed areas, such as clearcuts, than in
undisturbed stands [19].  Seed production normally begins when trees are
20 to 30 years old [73].  However, open-grown trees may produce seed by
age 10 [19,50].  Cones average about three to six seeds, but cones are
often numerous and heavy seed crops are common.  Average annual seed
crops vary from 100,000 to 1,000,000 seeds per acre
(247,000-2,470,000/ha) in coastal forests and from 22,000 to 111,000 per
acre (54,000-274,000/ha) in the interior [50].  Pure stands of western
redcedar may yield 60,704,168 seeds per acre (150,000,000/ha).  Poor
cone crops are rare [19].  Large seed crops occur every 3 to 4 years
[19,51].

Western redcedar seeds are small, 203,000 to 592,000 seeds per pound
(448,000-1,305/Kg) [8,50].  The seeds are dispersed primarily by wind.
However, the seeds have small wings and are not carried more than 400
feet (122 m) from the parent tree [8,48,50].




SEASONAL DEVELOPMENT : 
The reproductive cycle of western redcedar occurs over approximately 16
months.  Phenology varies between coastal and interior regions.  For
trees in the middle of the coastal distribution on Vancouver Island,
pollen and seed cones develop in early June.  Pollen forms in late
February or early March of the second season.  Pollination occurs within
1 to 2 weeks usually in March but may begin as early as mid-February in
mild coastal areas or as late as early April at higher elevations.
Pollination in March is most common [57].  Fertilization occurs in late
May.  Cones mature in October.  West of the Cascade Range, cone maturity
is usually reached in 5 months, but in northern Idaho it takes 3 months.
Major seedfall occurs during October and November in both the interior
and coast range [50].  Dry warm weather can cause earlier seed release.
Some seeds may be retained in the cones and gradually shed throughout
the winter [19].  Where moisture and temperature conditions are
favorable, germination can occur in the autumn, winter, or spring [50].
Along the coast region, seeds generally germinate in either fall or
spring [8].


## Chamaecyparis nootkatensis

### https://www.fs.fed.us/database/feis/plants/tree/calnoo/all.html

REGENERATION PROCESSES : 
Sexual:  The frequency of good seed crops is irregular (4 or more years)
[59], and germination rates are low [35].  A germination rate of around
12 percent can be obtained with a warm stratification (30 days at 68 to
86 degrees Fahrenheit [20-30 deg C]) followed by a moist stratification
(30 days at 40 degrees Fahrenheit [4 deg C]).  A tetrazolium stain has
been recommended for a test of seed viability [23].  The seed are quite
small with an average of 108,000 seeds per pound (240,000 seeds/kg)
[23,24].  The seed can be stored dry at 32 degrees Fahrenheit (0 deg C)
for 3 to 5 years [59].  Bower and others [5] recommend foliar
application of gibberellin A3 to increase flowering and filled seed.
From the parent tree the mean dissemination distance is about 400 feet
(120 m) [24].  Germination is epigeal [24], and mineral soil or well
decomposed organic matter are the preferred germination substrates [37].

Vegetative:  Alaska-cedar reproduces asexually by layering.  It layers
readily under the deep, heavy coastal snowpacks [49].  Vegetative
reproduction is the method of choice to meet the demands for
containerized stock, due to the low germination rate and infrequent good
seed crops [35].  Cuttings, treated with indolebutyric acid and potted
in the greenhouse, were ready for planting in 1 year [24].  Clones have
advantages over seedlings such as fewer multiple leaders and uniformity
in size [35].  Karlsson [34] and Karlsson and Russell [35] provide
in-depth information on age of the donor, clone survival, establishment,
and planting guidelines.


## Taxus brevifolia

### https://www.fs.fed.us/database/feis/plants/tree/taxbre/all.html


REGENERATION PROCESSES : 
Pacific yew can establish beneath a closed forest canopy by seed or by
vegetative means [49].  In many areas, layering is the primary mode of
reproduction, but seedlings are also common on some sites [2].

Seed:  Most species of yew (Taxus spp.) produce at least some seed
annually [65].  Seeds can remain viable for 5 or 6 years if properly
stored [65].  Conclusive evidence is lacking, but some researchers have
suggested that seed may be stored in the soil [31].  Seed is commonly
dispersed by birds, and some long-distance transport is possible [50].
Passage through avian digestive tracts may affect seed dormancy [11].

Germination:  Seeds of Pacific yew have a "strong but variable" dormancy
[65] and generally require stratification before germination can begin
[53].  In laboratory experiments, seeds germinated well after prolonged
warm and cold stratification [65].  Seed can be planted 0.4 to 0.5 inch
(10-13 mm) in depth and subjected to alternating day (86 degrees
Fahrenheit [30 deg C]) and night (68 degrees Fahrenheit [20 deg C])
temperatures for at least 28 days.  However, even when properly treated,
some seed may not germinate until the second spring.  Results of an
experimental test were as follows [65]:

  stratification         temp.        duration      germ. capacity
  warm        cold     day  night     (days)        (avg. %)   (range)

  ---         ---      86 F  68 F       60             55       50-99   

In other laboratory tests, average germination ranged from 50 to 60
percent [77].  Under natural conditions, germination may not take place
until the second year [65].

Seedling establishment:  Seedling establishment is generally more
favorable beneath a canopy than in canopy gaps [14].  Means [52]
observed seedling densities of 0.4 per acre (1/ha) in gaps but noted 47
per acre (115/ha) beneath a canopy in the western Cascades of Oregon.
Seedlings are reportedly uncommon in undisturbed situations but are
often abundant in partially cut areas where yew is present [11].



## andropogon gerardii 

### https://www.fs.fed.us/database/feis/plants/graminoid/andger/all.html

REGENERATION PROCESSES : 
Although big bluestem is capable of both vegetative and sexual modes of
regeneration throughout its range, vegetative regeneration is most
prevalent.  Vegetative regeneration occurs with the initiation of growth
from rhizomes.  Parent tillers consist of a rhizome, four to six
adventitious roots, and an aerial shoot, and develop mature buds in leaf
axils on their rhizomes [84].  New tillers begin as buds on the rhizomes
of their parent tillers.  These buds grow horizontally from their parent
before emerging from the soil surface.  In Kansas, rhizome buds begin to
swell and break open in late March, and by the end of April, growth of
tillers and elongation of the rhizomes occurs and continues throughout
the summer until August [105].  McKendrick and others [84] observed that
each tiller averaged two tiller offspring during the succeeding growing
season, with about half of these second-year tillers being vegetatively
reproductive but producing no seed.  Once a clone is produced, it can
live and reproduce for an unknown number of years, perhaps centuries
[105].

In undisturbed stands only a small proportion of tillers flower each
year.  This has been attributed to the irregularity of moisture and
temperatures at blooming time [51,68].  Drought
severely reduces
flowering, but flowering increases during a wet year following a
drought.  Big bluestem also flowers abundantly following fire [68].

Abrams [1] found only 2.5 viable seeds per 1,352 cubic centimeters of
soil in undisturbed stands where big bluestem comprised 77 percent of
the canopy cover.  This almost total absence of buried seeds suggests a
high dependence on vegetative reproduction.  The limited germination in
big bluestem may be attributed to the following:  (1) seed predation by
birds, mammals, or insects either after having fallen or while still on
the plant; (2) fungus and bacteria during wet seasons which cause the
seeds to rot; and (3) the very limited space for germination in prairie
stands.  Carter and others [16] reported that 40 percent of the seed
crop of the big bluestem cultivar 'Pawnee' was destroyed by a midge in
certain seed production fields.  This midge is widespread in North
America and occurs in many areas where native stands of big bluestem
remain.



## sorghastrum nutans 

### https://www.fs.fed.us/database/feis/plants/graminoid/sornut/all.html


SEASONAL DEVELOPMENT : 
Indiangrass starts growth in midspring from short rhizomes.  In Oklahoma
growth began on April 6th [60].  It matures from September to November
[69].  Across its range, flowering occurs latest in the southeast and
earliest in the northwest.  Flowering patterns may be somewhat genetic.
Flowering dates of plants transplanted in Nebraska from several regions
were similar to those of the plants where they originated [51].
Flowering dates for different regions have been reported as follows:

Area                   Flowering Date             Authority

Texas                  September to November      Gould 1937
Oklahoma               September 1 to 19          Rice 1950, Bogle 1989
Kansas                 mid-September              Albertson
Missouri               August                     Rabinowitz & others 1989
eastern Nebraska       August                     Steiger 1930
North Dakota           mid-July to mid-August     Manske 1980




## sporobolus compositus 

### https://www.fs.fed.us/database/feis/plants/graminoid/spocom/all.html#Seed%20production

Seed production: Although variable [23], composite dropseed seed production is generally high [32,50,187]. In little bluestem prairie near Hayes, Kansas, a 3-year study found that composite dropseed averaged 83.4 to 91.3 caryopses per 100 florets. In all years, composite dropseed had the highest average number of caryopses per 100 florets of the 7 grasses measured. In big bluestem prairie in 1941, composite dropseed had the largest seed yield (909.3 lbs/acre) of the 5 grasses investigated [32]. On 3 prairie sites in west-central Minnesota, seed harvesting in September of 1983 yielded approximately 0.51 kg/ha of live composite dropseed seed [168]. Seed production of composite dropseed plants in 2 populations in northeastern South Dakota was variable when grown in a greenhouse over a 3-year period, ranging from 3.8 g of seed/plant to 17.8 g of seed/plant. Composite dropseed from a roadside population averaged 11.9 grams of seed/plant, significantly (P<0.01) more than the 8.1 grams of seed/plant produced by composite dropseed in a native prairie. Seeds from the roadside population were also significantly (P<0.01) larger than seeds from the native prairie [23]. At peak seed set, Stevens [219] collected 4,540 mature seeds from a single composite dropseed plant that was "well developed" and "growing with comparatively little competition." Mississippi dropseed had low seed set following transplanting. It is unclear if this would occur in wild populations [187].

Composite dropseed plants may produce viable seed within a year. On a "prairie reconstruction" site at a Kansas museum, composite dropseed flowered in the first year [178]. According to a review, Weaver and Fitzpatrick (1934) observed composite dropseed produce flowering stalks in the 1st year [65]. Composite dropseed plants germinated in a greenhouse and transplanted to a garden in mid-May produced viable seed in the 1st year [22]. A review notes observations of composite dropseed reaching maturity in the 1st (Bender unpublished) or 2nd year (Christiansen and Landers 1969) [19].



## dichanthelium oligosanthes 


### https://plants.usda.gov/core/profile?symbol=DIOLS

Establishment
Growth generally initiates in the late fall. The basal
leaves form rosettes, which grow little during the
winter, but stay green. It produces seedheads and
leaves along the stems in the spring. A few plants
start growth in the spring and in the fall produce a
reduced seedhead partly protected by the leaves.
Low panicums grow on all sites, except marshes.

## schizachyrium scoparium 


### https://www.fs.fed.us/database/feis/plants/graminoid/schsco/all.html


 SEASONAL DEVELOPMENT:
Little bluestem is a warm season grass [39]. It starts growth in the spring with only a few leaves but then fills out rapidly. Using stored carbohydrates, new shoots develop from axillary buds below the ground surface. Little bluestem begins growth in late spring after cool-season grasses have already developed. In Oklahoma, little bluestem begins growth about 20 days earlier than big bluestem [7]. Little bluestem begins growth in early April in the southern part of its range and in May in the northern part of its range [36,37,123,155,236]. 

Miller [192] observed that little bluestem phenology follows a well-defined pattern, in which the date of anthesis and the period of active growth are directly related to the length of the growing season. This pattern was also noted by McMillan [187,188], who found that plants of northern and western origin flowered earliest (usually July), while plants of southern and eastern origin flowered later (around October). Plants from northern origins mature under long-day lengths and a short frost-free period. Plants from southern origin are adapted to shorter day lengths and a long frost-free period. Flowering is stimulated by and may occur earlier as the result of fire, particularly when it occurs in late spring (see Plant Response to Fire) [138]. Little bluestem shows considerable ecotypic variation in relation to the time of flowering [148,163,187,188]. Time of flowering in several states is [7,10,95,123,155,226,245,263]: 

## bouteloua curtipendula 


### https://www.fs.fed.us/database/feis/plants/graminoid/boucur/all.html

SEASONAL DEVELOPMENT:
Sideoats grama starts growth in mid-spring, and generally flowers between July and September [212]. In native tallgrass prairie in central Oklahoma, anthesis occurs from July to September, seedlings sprout in November and December and in March and April, and seed formation and dissemination occur from July through November [2]. The growing period for sideoats grama in the southern Great Plains is April through October [182]. In Wisconsin, root crown growth occurred from early April through mid-July, then again from early to mid-August. Production of secondary and tertiary shoots occurred from mid-March through late October, and anthesis occurred from mid-July to mid-August [148]. Production of shoots slowed during flower production but did not cease at any time during the growing season. In general, sideoats grama flowers from April to October [105]. Flowering dates for sideoats grama vary with location, and are summarized in the following table:

Location 	Beginning of Flowering 	End of flowering
OK 	June 	July [173]
IL, VA, WV, CO, WY 	July 	September [142,193,226]
CA 	April 	October [145]
NM 	May 	October [128]


## panicum virgatum 



REGENERATION PROCESSES : 
Switchgrass reproduces both sexually and vegetatively.  Rhizomes are
responsible for vegetative expansion, but spreading ability depends upon
growth form.  Some rhizomes of sod-forming ecotypes may extend to
lengths of 1 to 2 feet (0.3-0.6 m), while those of bunch-forming
ecotypes may extend only a few inches [7,77].  The primary site of
nonstructural carbohydrate storage is in the stem bases, roots, and
rhizomes [72].

Switchgrass generally produces abundant seed.  Natural stands often
yield 100 pounds of seeds per acre (112 kg/ha), and cultivated stands
may yield 300 to 500 pounds of seeds per acre (336-561 kg/ha) [78].  The
seeds are shed in fall or winter and require winter dormancy before they
germinate in the spring [61].  Germination begins when soil temperatures
reach 68 degrees Fahrenheit (20 deg C) [72].  Seed collected from
southeastern Montana and northeastern Wyoming had relatively high
germination rates; 70 to 90 percent at temperatures between 68 and 86
degrees Fahrenheit (20-30 deg C) [22].  Fulbright and others [26]
reported germinative capacity of 40 to 70 percent.

The importance of switchgrass seedling recruitment into prairie habitats
is scarcely discussed in scientific literature.  In tallgrass prairie,
switchgrass tillering and rhizome production generally begins 5 to 7
weeks after germination, unless competition is severe [77].  Three
months after germination, plants may be 12 to 20 inches (30-50 cm) tall,
and roots may be 12 to 30 inches (30-76 cm) deep [77].  

On sand dunes bordering Lake Erie, switchgrass maintains and expands
stands primarily through seedling establishment.  On the dunes,
seedlings emerged from seeds buried at depths of 0 to 4.3 inches (0-11
cm) and withstood considerable postemergence sand burial [79].




## poa pratensis 


### https://www.fs.fed.us/database/feis/plants/graminoid/poapra/all.html

EASONAL DEVELOPMENT : 
Kentucky bluegrass is one of the first grasses to resume growth in late
winter or early spring.  It grows rapidly, and in many states it flowers
in May [19,27].  In Kentucky and Missouri, seeds are mature by mid-June
[125].  By midsummer plants become nearly dormant.  With cool
temperatures and precipitation, growth resumes in the fall and continues
until daytime temperatures approach freezing [97,105].

Flowering time for several states is as follows:

Montana - late May and early June [97]
North Dakota - late May and early June [69]
Nebraska - May [105]

Kentucky bluegrass phenology was studied over a 3-year period on the
Sheyenne National Grasslands in southeastern North Dakota.  Timing of
phenological events was as follows (average dates for the 3 years
studied) [69]:

Resumption of spring growth - green leaves observed during snowmelt in
mid-March, but rapid growth began in early April.

Flowering - flower stalks appeared in mid-May.  Most flowering occurred
in late May and early June.  Nearly all plants completed anthesis within
one week.

Seed maturation - mature seeds were observed in mid- to late June.  Seed
stalks became dried after anthesis and were easily removed by wind.
Most stalks were removed by midsummer. 

Senescence and regrowth - maximum leaf height occurred in mid-June and
leaf senescence occurred shortly thereafter.  Plants were semidormant
during midsummer.  Large amounts of vegetative regrowth began in late
July and early August.  Forty percent of leaves present at the end of
August were new growth, which continued for a short time after the first
hard frost.



## koeleria macrantha 



### https://www.fs.fed.us/database/feis/plants/graminoid/koemac/all.html

REGENERATION PROCESSES:
Regeneration is accomplished by seed, which ripens late summer to fall [110] and by sprouting from the residual plant [23,120]. Prairie Junegrass seeds are relatively small (4,000 gram-1 reported by Eddleman [40] and 3,125 gram-1 reported by Nernberg [83]) and of low viability [78,83,110].

Temperature, soil moisture and seasonality provide cues for germination of prairie Junegrass [40,104,112]. A comparison of germination and emergence of prairie Junegrass at 45 (7°C), 55 (13°C), 64 (18°C) and 80 (27°C) degrees Fahrenheit, showed the greatest % emergence at 64 degrees Fahrenheit (18°C) [104]. Blake [18] observed good germination within silt loam at 1/2 and 1/3 saturation. Prairie Junegrass also possesses the ability to germinate under periods of water stress. Germination responses were observed at water potential between 0 to 12 bars [40].

A seedbank evaluation of prairie Junegrass found that seed was infrequent or absent within sampled areas, although prairie Junegrass was a significant member of the plant community [112]. Seedbank germination response to seasonality was also measured. Prairie Junegrass showed no seedling establishment during early spring (May and June) [112]. Large peaks were observed during late summer and autumn [112].

The presence of mycorrhizae may have a significant (p< 0.05) positive effect on seedling emergence [51]. Neutral effects have also been reported [124].


## eragrostis spectabilis 



## sporobolus heterolepis


### https://www.fs.fed.us/database/feis/plants/graminoid/spohet/all.html

SEASONAL DEVELOPMENT : 
Prairie dropseed flowers and fruits from August through November


## elymus canadensis 

### https://www.fs.fed.us/database/feis/plants/graminoid/elycan/all.html

REGENERATION PROCESSES:
Canada wildrye may reproduce through seed or vegetative production. However, it does not rely heavily on vegetative reproduction [86,96]. Canada wildrye produces a high ratio of reproductive to vegetative stems [31] and persistence is generally maintained through production of seed [96].

Seed:
Canada wildrye may outcross [36,76] or self-fertilize [6,36,76]. Sanders and Hamrick [76] found Canada wildrye most often self-fertilizes throughout the northern Great Plains with outcrossing rates varying between populations. Gable [36] observed a much greater outcrossing percentage than that of self-fertilization.

Throughout its distribution, Canada wildrye seed usually matures in the early fall [21]. In the southern portion of its' range, Canada wildrye seed most often mature in July with northern populations maturing in August [98]. Seed yields can average 300 to 400 lbs. (136-181 kg) per acre from native stands [49]. There is no report on seed dispersal mechanisms. However, the presence of long awns suggests the potential for long distance dispersal by animals.

Canada wildrye seeds are highly germinable, showing the best germination in soils with high water content [13]. Seedlings are vigorous [49,98] and usually establish quickly [98]. Robocker and others [74] found Canada wildrye seeds required an average of 8 days before emergence. Seeds were planted in flats at 0.125 to 0.25 inch (0.318-0.64 cm) depths containing a mixture of 1/2 sand and 1/2 Miami silt loam topsoil and germinated in greenhouse conditions at 60 to 65 degrees Fahrenheit (16-18 °C). Average emergence was 54.7%.
